[colors.bright]
black = "0x6f6f6f"
blue = "0xc2e3ff"
cyan = "0xc0e9f8"
green = "0xd6fcba"
magenta = "0xffc6ff"
red = "0xfe978b"
white = "0xffffff"
yellow = "0xfffed5"

[colors.cursor]
cursor = "#ECEFF4"
text = "#3B4252"

[colors.normal]
black = "0x26282a"
blue = "0x8bbce5"
cyan = "0xa2e1f8"
green = "0xb4fb73"
magenta = "0xffb2fe"
red = "0xff8878"
white = "0xf1f1f1"
yellow = "0xfffcb7"

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[cursor.style]
blinking = "Never"

[font]
size = 10.0

[font.bold]
family = "Ubuntu Mono"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono"
style = "Italic"

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[window]
decorations = "None"
opacity = 0.95

[window.padding]
x = 5
y = 5
